language: c
 
env:
 global:
  - EnableNuGetPackageRestore=true 
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - wget https://nuget.org/nuget.exe
  - mono --runtime=v4.0 nuget.exe update --self
 
script:
  - xbuild ReSpekter.sln